// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a4bec27e-1a2d-44ee-b649-13363417d678",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aw3Z5746H",
    "aws_user_pools_web_client_id": "1kmdlvsict7dn7pl19pfvaausk",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplify-js-app64cae81fc6be46779d9ad78356d0da90app-amplify",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api595d75c2",
            "endpoint": "https://d0y0liwzlf.execute-api.us-east-1.amazonaws.com/amplify",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
